"""
Static watchlist data — thesis, analyst target, catalyst, risk notes.
Edit this file to add/remove tickers. Prices are fetched live from FMP.
"""

WATCHLIST = [
    # ---- AI / Semiconductors ----
    {
        "ticker": "MRVL",
        "region": "US",
        "name": "Marvell Technology",
        "sector": "AI/Semis",
        "target": 190,
        "thesis": "AI custom-silicon for hyperscalers. Recent target hikes (Citi $215, Stifel $210) suggest re-rating room.",
        "catalyst": "Next earnings; hyperscaler capex",
        "risk": "High beta — falls with any AI-sentiment shock",
    },
    {
        "ticker": "MU",
        "region": "US",
        "name": "Micron Technology",
        "sector": "AI/Semis",
        "target": 160,
        "thesis": "WATCH ONLY: Forward-P/E thesis broken at current price after parabolic run. Kept for visibility.",
        "catalyst": "HBM3E ramp; DRAM cycle",
        "risk": "Memory is cyclical — sharp drawdowns possible",
    },
    {
        "ticker": "LRCX",
        "region": "US",
        "name": "Lam Research",
        "sector": "AI/Semis",
        "target": 315,
        "thesis": "WFE spend guide raised to $140B. Quality way to play AI capex without single-customer risk.",
        "catalyst": "WFE cycle; earnings",
        "risk": "Already up big — less torque from here",
    },
    {
        "ticker": "FORM",
        "region": "US",
        "name": "FormFactor",
        "sector": "AI/Semis",
        "target": 175,
        "thesis": "Q1 beat → Craig-Hallum upgrade to Buy/$175. Smaller-cap semi-test exposure.",
        "catalyst": "Semi-test demand; next earnings",
        "risk": "Smaller cap, more volatile",
    },
    {
        "ticker": "ORCL",
        "region": "US",
        "name": "Oracle (S&P 500)",
        "sector": "AI/Semis",
        "target": 260,
        "thesis": "AI cloud infrastructure pure-play (OCI, Stargate). Off the $345 high, consensus ~$260 → ~35% upside.",
        "catalyst": "Cloud revenue acceleration; next earnings",
        "risk": "Capex-heavy build-out, margin pressure",
    },

    # ---- Biotech ----
    {
        "ticker": "NUVL",
        "region": "US",
        "name": "Nuvalent",
        "sector": "Biotech",
        "target": 138,
        "thesis": "PDUFA Sept 18, 2026 for zidesamtinib (ROS1 lung cancer). $1.4B cash through 2029.",
        "catalyst": "FDA decision Sep 18, 2026",
        "risk": "Binary FDA event — sharp move either way",
    },
    {
        "ticker": "RLAY",
        "region": "US",
        "name": "Relay Therapeutics",
        "sector": "Biotech",
        "target": 21,
        "thesis": "12 buys / 0 holds. FDA Breakthrough designation for zovegalisib (PI3Kα).",
        "catalyst": "ESMO TAT data",
        "risk": "Clinical-stage — single readout drives stock",
    },
    {
        "ticker": "SDGR",
        "region": "US",
        "name": "Schrödinger",
        "sector": "Biotech",
        "target": None,
        "thesis": "Physics+AI drug-discovery platform. Trading near 52-wk low. Lumpy royalty/milestone model.",
        "catalyst": "Pharma collaboration milestones",
        "risk": "Royalty/milestone model — lumpy revenue",
    },

    # ---- Energy / Industrials ----
    {
        "ticker": "UEC",
        "region": "US",
        "name": "Uranium Energy Corp",
        "sector": "Energy",
        "target": 26.75,
        "thesis": "H.C. Wainwright Buy/$26.75. Cleanest pure-play on nuclear demand (uranium +28% by 2030).",
        "catalyst": "Uranium spot price; US production restart",
        "risk": "Speculative, commodity-driven",
    },
    {
        "ticker": "CCJ",
        "region": "US",
        "name": "Cameco",
        "sector": "Energy",
        "target": None,
        "thesis": "Higher-quality uranium play vs. UEC; less torque but lower risk.",
        "catalyst": "Contract pricing cycle",
        "risk": "Already extended after big move",
    },
    {
        "ticker": "DEC",
        "region": "US",
        "name": "Diversified Energy",
        "sector": "Energy",
        "target": 22.57,
        "thesis": "Strong Buy consensus, ~50% upside. Natural gas with dividend yield.",
        "catalyst": "Henry Hub strength",
        "risk": "Asset-heavy mature wells — debt risk",
    },
    {
        "ticker": "DVN",
        "region": "US",
        "name": "Devon Energy",
        "sector": "Energy",
        "target": None,
        "thesis": "Morningstar's most-undervalued energy name. Permian focus.",
        "catalyst": "Buybacks; oil price",
        "risk": "Pure oil-price exposure",
    },
    {
        "ticker": "GRC",
        "region": "US",
        "name": "Gorman-Rupp",
        "sector": "Energy",
        "target": None,
        "thesis": "Niche industrial (pumps) riding water infra + AI data-center cooling.",
        "catalyst": "Order backlog growth",
        "risk": "Industrial cyclical",
    },

    # ---- Financials ----
    {
        "ticker": "BAC",
        "region": "US",
        "name": "Bank of America",
        "sector": "Financials",
        "target": 65,
        "thesis": "~11x forward P/E. CFRA $65. Benefits from any rate easing.",
        "catalyst": "NII inflection; rate cuts",
        "risk": "Recession would hit credit costs",
    },
    {
        "ticker": "JPM",
        "region": "US",
        "name": "JPMorgan Chase",
        "sector": "Financials",
        "target": 340,
        "thesis": "CFRA $340 target. Quality compounder.",
        "catalyst": "Capital return",
        "risk": "Lower torque vs. peers",
    },
    {
        "ticker": "TD",
        "region": "US",
        "name": "Toronto-Dominion",
        "sector": "Financials",
        "target": None,
        "thesis": "~12x earnings — post-AML-fine rebuild. Cheap vs. Big Six peers.",
        "catalyst": "Resolution of US regulatory overhang",
        "risk": "Slow rebuild; regulator-driven",
    },

    # ---- Consumer / Comm Services (S&P 500 adds) ----
    {
        "ticker": "CHTR",
        "region": "US",
        "name": "Charter Communications (S&P 500)",
        "sector": "Consumer/Comm",
        "target": 245,
        "thesis": "Near 52-wk low after collapse from $422. Consensus ~$245 → ~70% upside. High-upside speculation.",
        "catalyst": "Cox merger close; sub trends stabilize",
        "risk": "Hold rating — fixed-wireless competition, margin pressure",
    },
    {
        "ticker": "GM",
        "region": "US",
        "name": "General Motors (S&P 500)",
        "sector": "Consumer/Comm",
        "target": 96,
        "thesis": "Forward P/E ~7, cheapest auto in the index. Bull case to $126.",
        "catalyst": "Q2 earnings; buyback pace; EV strategy",
        "risk": "Cyclical end-market; China weakness",
    },

    # ---- International ----
    {
        "ticker": "POLYCAB.NS",
        "region": "IN",
        "name": "Polycab India",
        "sector": "Intl",
        "target": None,
        "thesis": "Market leader in wires/cables, India infra beneficiary, ~zero debt.",
        "catalyst": "Capex cycle; Make-in-India",
        "risk": "INR exposure; mid-cap volatility",
    },
    {
        "ticker": "HMC",
        "region": "US",
        "name": "Honda Motor (ADR)",
        "sector": "Intl",
        "target": None,
        "thesis": "USD-listed ADR. Cheap vs. Toyota on multiples; Japan governance reform.",
        "catalyst": "EV strategy clarity; yen direction",
        "risk": "China auto market weakness",
    },
]

SECTOR_ORDER = ["AI/Semis", "Biotech", "Energy", "Financials", "Consumer/Comm", "Intl"]
